### ISSUE TITLE
如何修改抽卡结果中的每排头像个数？

### ISSUE THREAD

**Issue by homileak** [azmiao/uma_gacha#1]
非常抱歉以issue的形式提出这个问题，您的插件很棒，没有任何错误就运行了起来，很流畅。
不过抽卡结果的显示是一排10个头像，在手机版QQ上图片缩略显示并不全，要点开来看，点开的话，因为图片横向太长了，要放大看，不是特别的方便。
所以我想把每一行的头像数目调整为5

我自己也有尝试，在utli.py找到了看上去像是控制图片生成的代码

`async def generate_img(card_set: Union[Set[BaseData], List[BaseData]], game_name: str, star_list: list) -> str:`
`    # try:`
`    img_list = []`
`    background_list = []`
`    for x in card_set:`
`        pyname = cn2py(x.name)`
`        img_list.append(DRAW_PATH + f'/draw_card/{game_name}/{pyname}.png')`
`    img_len = len(img_list)`
`    w = 100 * 10`
`    if img_len <= 10:`
`        w = 100 * img_len`
`        h = 100`
`    elif img_len % 10 == 0:`
`        h = 100 * int(img_len / 10)`
`    else:`
`        h = 100 * int(img_len / 10) + 100`
`    card_img = await asyncio.get_event_loop().run_in_executor(None, _pst, h, img_list, game_name, background_list)`
`    num = 0`
`    for n in star_list:`
`        num += n`
`    A = CreateImg(w, h)`
`    A.paste(card_img)`
`    return A.pic2bs4()`

我将里面的10改成了5

`async def generate_img(card_set: Union[Set[BaseData], List[BaseData]], game_name: str, star_list: list) -> str:`
`    # try:`
`    img_list = []`
`    background_list = []`
`    for x in card_set:`
`        pyname = cn2py(x.name)`
`        img_list.append(DRAW_PATH + f'/draw_card/{game_name}/{pyname}.png')`
`    img_len = len(img_list)`
`    w = 100 * 5`
`    if img_len <= 5:`
`        w = 100 * img_len`
`        h = 100`
`    elif img_len % 5 == 0:`
`        h = 100 * int(img_len / 10)`
`    else:`
`        h = 100 * int(img_len / 10) + 100`
`    card_img = await asyncio.get_event_loop().run_in_executor(None, _pst, h, img_list, game_name, background_list)`
`    num = 0`
`    for n in star_list:`
`        num += n`
`    A = CreateImg(w, h)`
`    A.paste(card_img)`
`    return A.pic2bs4()`

有效果，抽卡结果的图片确实横向每排只有5个头像了。
![4104](https://user-images.githubusercontent.com/48946260/154484877-7bf7e927-3e49-4b5b-8de5-a7a9ab372454.png)

但是很快我发现这样子实际上显示不全，也就是横向上仍然是10个头像，只不过只显示了5个，多余的都被截掉了，最明显的就是模拟10连的时候，只显示5个。
![3905](https://user-images.githubusercontent.com/48946260/154484919-b9b50780-57b6-4a03-b3e2-6a1c788a5350.png)

因为我只能看懂这些了，其他的几个py我看了下，基本看不懂，周围也没有懂py的人，只能问下您如何修改了。

**Comment by azmiao** [comment]
确实很有道理，这就改

**Comment by homileak** [comment]
> 确实很有道理，这就改

非常感谢！
